apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapplication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springapplication
  template:
    metadata:
      labels:
        app: springapplication
    spec:
      containers:
        - name: springapplication
          image: tumuladeepak/springbootapplication:v1
          env:
            - name: ENV_VALUE
              value: "Hello from AWS Cluster Kubernetes using CI-CD!!"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: springapplication
spec:
  type: LoadBalancer
  selector:
    app: springapplication
  ports:
    - port: 80
      targetPort: 8080